### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by sshelton76** [whs/tweetnacl-sealed-box#1]
It would make a lot of sense to add a description of WHY someone would want to do this.

To my mind it comes down to what can be gleaned by outside observers from the meta-data derived by monitoring the transit.  Even without knowing the contents of a message, a lot of information can be derived by knowing the sender and the recipient.  If the sender can mask their identity, then half that meta-data goes away.  If both the sender and the recipient can mask their identities at the same time, then all meta-data goes away and it frustrates potential eavesdroppers.

**Comment by whs** [comment]
This is an encryption library. How you transmit it to receiver in a way that is secure is a protocol, which is out of the scope of the project.
